<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\ProductImage;
use App\Models\ProductVariant;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            // 1. Stars Cosmic Heavy Tee (Oversized T-Shirts)
            [
                'id' => 1,
                'category_id' => 1,
                'name' => 'Stars Cosmic Heavy Tee',
                'slug' => 'stars-cosmic-heavy-tee',
                'description' => 'T-shirt bergaya streetwear dengan potongan boxy-oversized menggunakan bahan 100% 24s Heavy Cotton (240 GSM). Dilengkapi grafis cosmic screen-printed berdaya tahan tinggi di bagian belakang.',
                'base_price' => 199000,
                'is_featured' => true,
                'is_active' => true,
                'images' => [
                    [
                        'image_url' => 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=80',
                        'alt_text' => 'Tampak Depan - Stars Cosmic Heavy Tee',
                        'is_primary' => true,
                        'sort_order' => 1,
                    ],
                    [
                        'image_url' => 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&auto=format&fit=crop&q=80',
                        'alt_text' => 'Tampak Belakang - Stars Cosmic Heavy Tee',
                        'is_primary' => false,
                        'sort_order' => 2,
                    ],
                ],
                'variants' => [
                    [
                        'id' => 101,
                        'size' => 'S',
                        'color_name' => 'Cosmic Black',
                        'color_hex' => '#1E1E24',
                        'sku' => 'STM-CSM-BLK-S',
                        'additional_price' => 0.00,
                        'stock_quantity' => 12,
                    ],
                    [
                        'id' => 102,
                        'size' => 'M',
                        'color_name' => 'Cosmic Black',
                        'color_hex' => '#1E1E24',
                        'sku' => 'STM-CSM-BLK-M',
                        'additional_price' => 0.00,
                        'stock_quantity' => 0, // Out of stock for testing
                    ],
                    [
                        'id' => 103,
                        'size' => 'L',
                        'color_name' => 'Cosmic Black',
                        'color_hex' => '#1E1E24',
                        'sku' => 'STM-CSM-BLK-L',
                        'additional_price' => 0.00,
                        'stock_quantity' => 8,
                    ],
                    [
                        'id' => 104,
                        'size' => 'XL',
                        'color_name' => 'Cosmic Black',
                        'color_hex' => '#1E1E24',
                        'sku' => 'STM-CSM-BLK-XL',
                        'additional_price' => 10000.00,
                        'stock_quantity' => 4,
                    ],
                    [
                        'id' => 105,
                        'size' => 'S',
                        'color_name' => 'Washed Grey',
                        'color_hex' => '#707070',
                        'sku' => 'STM-CSM-GRY-S',
                        'additional_price' => 0.00,
                        'stock_quantity' => 6,
                    ],
                    [
                        'id' => 106,
                        'size' => 'M',
                        'color_name' => 'Washed Grey',
                        'color_hex' => '#707070',
                        'sku' => 'STM-CSM-GRY-M',
                        'additional_price' => 0.00,
                        'stock_quantity' => 10,
                    ],
                    [
                        'id' => 107,
                        'size' => 'L',
                        'color_name' => 'Washed Grey',
                        'color_hex' => '#707070',
                        'sku' => 'STM-CSM-GRY-L',
                        'additional_price' => 0.00,
                        'stock_quantity' => 5,
                    ],
                    [
                        'id' => 108,
                        'size' => 'XL',
                        'color_name' => 'Washed Grey',
                        'color_hex' => '#707070',
                        'sku' => 'STM-CSM-GRY-XL',
                        'additional_price' => 10000.00,
                        'stock_quantity' => 2,
                    ],
                ],
            ],

            // 2. Stars Acid-Wash Vintage Tee (Oversized T-Shirts)
            [
                'id' => 2,
                'category_id' => 1,
                'name' => 'Stars Acid-Wash Vintage Tee',
                'slug' => 'stars-acid-wash-vintage-tee',
                'description' => 'Kaos vintage acid-wash bertekstur unik dan lembut di kulit. Dibuat dengan teknik pencucian khusus menghasilkan gradasi warna autentik, jahitan rantai ganda pada leher dan lengan untuk ketahanan ekstra.',
                'base_price' => 189000,
                'is_featured' => true,
                'is_active' => true,
                'images' => [
                    [
                        'image_url' => 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&auto=format&fit=crop&q=80',
                        'alt_text' => 'Tampak Depan - Stars Acid-Wash Vintage Tee',
                        'is_primary' => true,
                        'sort_order' => 1,
                    ],
                    [
                        'image_url' => 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&auto=format&fit=crop&q=80',
                        'alt_text' => 'Detail Bahan - Stars Acid-Wash Vintage Tee',
                        'is_primary' => false,
                        'sort_order' => 2,
                    ],
                ],
                'variants' => [
                    [
                        'id' => 109,
                        'size' => 'S',
                        'color_name' => 'Vintage Charcoal',
                        'color_hex' => '#2F3542',
                        'sku' => 'STM-ACD-CHR-S',
                        'additional_price' => 0.00,
                        'stock_quantity' => 15,
                    ],
                    [
                        'id' => 110,
                        'size' => 'M',
                        'color_name' => 'Vintage Charcoal',
                        'color_hex' => '#2F3542',
                        'sku' => 'STM-ACD-CHR-M',
                        'additional_price' => 0.00,
                        'stock_quantity' => 8,
                    ],
                    [
                        'id' => 111,
                        'size' => 'L',
                        'color_name' => 'Vintage Charcoal',
                        'color_hex' => '#2F3542',
                        'sku' => 'STM-ACD-CHR-L',
                        'additional_price' => 0.00,
                        'stock_quantity' => 12,
                    ],
                    [
                        'id' => 112,
                        'size' => 'XL',
                        'color_name' => 'Vintage Charcoal',
                        'color_hex' => '#2F3542',
                        'sku' => 'STM-ACD-CHR-XL',
                        'additional_price' => 10000.00,
                        'stock_quantity' => 5,
                    ],
                    [
                        'id' => 113,
                        'size' => 'S',
                        'color_name' => 'Sand Beige',
                        'color_hex' => '#D1C7BD',
                        'sku' => 'STM-ACD-SND-S',
                        'additional_price' => 0.00,
                        'stock_quantity' => 8,
                    ],
                    [
                        'id' => 114,
                        'size' => 'M',
                        'color_name' => 'Sand Beige',
                        'color_hex' => '#D1C7BD',
                        'sku' => 'STM-ACD-SND-M',
                        'additional_price' => 0.00,
                        'stock_quantity' => 10,
                    ],
                    [
                        'id' => 115,
                        'size' => 'L',
                        'color_name' => 'Sand Beige',
                        'color_hex' => '#D1C7BD',
                        'sku' => 'STM-ACD-SND-L',
                        'additional_price' => 0.00,
                        'stock_quantity' => 6,
                    ],
                    [
                        'id' => 116,
                        'size' => 'XL',
                        'color_name' => 'Sand Beige',
                        'color_hex' => '#D1C7BD',
                        'sku' => 'STM-ACD-SND-XL',
                        'additional_price' => 10000.00,
                        'stock_quantity' => 3,
                    ],
                ],
            ],

            // 3. Stars Cyberpunk Graphic Tee (Oversized T-Shirts)
            [
                'id' => 3,
                'category_id' => 1,
                'name' => 'Stars Cyberpunk Graphic Tee',
                'slug' => 'stars-cyberpunk-graphic-tee',
                'description' => 'Kaos graphic neon print futuristik bergaya neo-Tokyo cyberpunk dengan potongan boxy drop-shoulder. Menggunakan sablon plastisol discharge berketahanan tinggi yang tidak kaku.',
                'base_price' => 179000,
                'is_featured' => false,
                'is_active' => true,
                'images' => [
                    [
                        'image_url' => 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800&auto=format&fit=crop&q=80',
                        'alt_text' => 'Tampak Depan - Stars Cyberpunk Graphic Tee',
                        'is_primary' => true,
                        'sort_order' => 1,
                    ],
                    [
                        'image_url' => 'https://images.unsplash.com/photo-1503342394128-c104d54dba01?w=800&auto=format&fit=crop&q=80',
                        'alt_text' => 'Tampak Belakang - Stars Cyberpunk Graphic Tee',
                        'is_primary' => false,
                        'sort_order' => 2,
                    ],
                ],
                'variants' => [
                    [
                        'id' => 117,
                        'size' => 'S',
                        'color_name' => 'Pitch Black',
                        'color_hex' => '#0A0A0C',
                        'sku' => 'STM-CYB-BLK-S',
                        'additional_price' => 0.00,
                        'stock_quantity' => 10,
                    ],
                    [
                        'id' => 118,
                        'size' => 'M',
                        'color_name' => 'Pitch Black',
                        'color_hex' => '#0A0A0C',
                        'sku' => 'STM-CYB-BLK-M',
                        'additional_price' => 0.00,
                        'stock_quantity' => 14,
                    ],
                    [
                        'id' => 119,
                        'size' => 'L',
                        'color_name' => 'Pitch Black',
                        'color_hex' => '#0A0A0C',
                        'sku' => 'STM-CYB-BLK-L',
                        'additional_price' => 0.00,
                        'stock_quantity' => 9,
                    ],
                    [
                        'id' => 120,
                        'size' => 'XL',
                        'color_name' => 'Pitch Black',
                        'color_hex' => '#0A0A0C',
                        'sku' => 'STM-CYB-BLK-XL',
                        'additional_price' => 10000.00,
                        'stock_quantity' => 4,
                    ],
                    [
                        'id' => 121,
                        'size' => 'S',
                        'color_name' => 'Off White',
                        'color_hex' => '#F5F5F0',
                        'sku' => 'STM-CYB-WHT-S',
                        'additional_price' => 0.00,
                        'stock_quantity' => 5,
                    ],
                    [
                        'id' => 122,
                        'size' => 'M',
                        'color_name' => 'Off White',
                        'color_hex' => '#F5F5F0',
                        'sku' => 'STM-CYB-WHT-M',
                        'additional_price' => 0.00,
                        'stock_quantity' => 7,
                    ],
                    [
                        'id' => 123,
                        'size' => 'L',
                        'color_name' => 'Off White',
                        'color_hex' => '#F5F5F0',
                        'sku' => 'STM-CYB-WHT-L',
                        'additional_price' => 0.00,
                        'stock_quantity' => 6,
                    ],
                    [
                        'id' => 124,
                        'size' => 'XL',
                        'color_name' => 'Off White',
                        'color_hex' => '#F5F5F0',
                        'sku' => 'STM-CYB-WHT-XL',
                        'additional_price' => 10000.00,
                        'stock_quantity' => 2,
                    ],
                ],
            ],

            // 4. Stars Oversized Heavy Hoodie (Hoodies & Sweaters)
            [
                'id' => 4,
                'category_id' => 2,
                'name' => 'Stars Oversized Heavy Hoodie',
                'slug' => 'stars-oversized-heavy-hoodie',
                'description' => 'Hoodie oversized 330 GSM cotton fleece dengan double-layered hood dan saku kangguru yang luas. Hangat, tebal, dan mempertahankan bentuk boxy sempurna saat dikenakan.',
                'base_price' => 349000,
                'is_featured' => true,
                'is_active' => true,
                'images' => [
                    [
                        'image_url' => 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&auto=format&fit=crop&q=80',
                        'alt_text' => 'Tampak Depan - Stars Oversized Heavy Hoodie',
                        'is_primary' => true,
                        'sort_order' => 1,
                    ],
                    [
                        'image_url' => 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&auto=format&fit=crop&q=80',
                        'alt_text' => 'Detail Bahan - Stars Oversized Heavy Hoodie',
                        'is_primary' => false,
                        'sort_order' => 2,
                    ],
                ],
                'variants' => [
                    [
                        'id' => 125,
                        'size' => 'M',
                        'color_name' => 'Jet Black',
                        'color_hex' => '#121212',
                        'sku' => 'STM-HOD-BLK-M',
                        'additional_price' => 0.00,
                        'stock_quantity' => 10,
                    ],
                    [
                        'id' => 126,
                        'size' => 'L',
                        'color_name' => 'Jet Black',
                        'color_hex' => '#121212',
                        'sku' => 'STM-HOD-BLK-L',
                        'additional_price' => 0.00,
                        'stock_quantity' => 12,
                    ],
                    [
                        'id' => 127,
                        'size' => 'XL',
                        'color_name' => 'Jet Black',
                        'color_hex' => '#121212',
                        'sku' => 'STM-HOD-BLK-XL',
                        'additional_price' => 15000.00,
                        'stock_quantity' => 6,
                    ],
                    [
                        'id' => 128,
                        'size' => 'XXL',
                        'color_name' => 'Jet Black',
                        'color_hex' => '#121212',
                        'sku' => 'STM-HOD-BLK-XXL',
                        'additional_price' => 25000.00,
                        'stock_quantity' => 3,
                    ],
                    [
                        'id' => 129,
                        'size' => 'M',
                        'color_name' => 'Forest Green',
                        'color_hex' => '#2D4A3E',
                        'sku' => 'STM-HOD-GRN-M',
                        'additional_price' => 0.00,
                        'stock_quantity' => 8,
                    ],
                    [
                        'id' => 130,
                        'size' => 'L',
                        'color_name' => 'Forest Green',
                        'color_hex' => '#2D4A3E',
                        'sku' => 'STM-HOD-GRN-L',
                        'additional_price' => 0.00,
                        'stock_quantity' => 7,
                    ],
                    [
                        'id' => 131,
                        'size' => 'XL',
                        'color_name' => 'Forest Green',
                        'color_hex' => '#2D4A3E',
                        'sku' => 'STM-HOD-GRN-XL',
                        'additional_price' => 15000.00,
                        'stock_quantity' => 4,
                    ],
                    [
                        'id' => 132,
                        'size' => 'XXL',
                        'color_name' => 'Forest Green',
                        'color_hex' => '#2D4A3E',
                        'sku' => 'STM-HOD-GRN-XXL',
                        'additional_price' => 25000.00,
                        'stock_quantity' => 0, // Out of stock for testing
                    ],
                ],
            ],

            // 5. Stars Minimalist Boxy Crewneck (Hoodies & Sweaters)
            [
                'id' => 5,
                'category_id' => 2,
                'name' => 'Stars Minimalist Boxy Crewneck',
                'slug' => 'stars-minimalist-boxy-crewneck',
                'description' => 'Sweater crewneck berpotongan cropped-boxy dengan bordir logo Stars Merch subtle di bagian dada kiri. Terbuat dari premium french terry yang adem dan nyaman digunakan seharian.',
                'base_price' => 299000,
                'is_featured' => false,
                'is_active' => true,
                'images' => [
                    [
                        'image_url' => 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&auto=format&fit=crop&q=80',
                        'alt_text' => 'Tampak Depan - Stars Minimalist Boxy Crewneck',
                        'is_primary' => true,
                        'sort_order' => 1,
                    ],
                    [
                        'image_url' => 'https://images.unsplash.com/photo-1578632767114-1f74a0bb2807?w=800&auto=format&fit=crop&q=80',
                        'alt_text' => 'Tampak Samping - Stars Minimalist Boxy Crewneck',
                        'is_primary' => false,
                        'sort_order' => 2,
                    ],
                ],
                'variants' => [
                    [
                        'id' => 133,
                        'size' => 'S',
                        'color_name' => 'Heather Grey',
                        'color_hex' => '#9E9E9E',
                        'sku' => 'STM-CRW-GRY-S',
                        'additional_price' => 0.00,
                        'stock_quantity' => 8,
                    ],
                    [
                        'id' => 134,
                        'size' => 'M',
                        'color_name' => 'Heather Grey',
                        'color_hex' => '#9E9E9E',
                        'sku' => 'STM-CRW-GRY-M',
                        'additional_price' => 0.00,
                        'stock_quantity' => 15,
                    ],
                    [
                        'id' => 135,
                        'size' => 'L',
                        'color_name' => 'Heather Grey',
                        'color_hex' => '#9E9E9E',
                        'sku' => 'STM-CRW-GRY-L',
                        'additional_price' => 0.00,
                        'stock_quantity' => 10,
                    ],
                    [
                        'id' => 136,
                        'size' => 'XL',
                        'color_name' => 'Heather Grey',
                        'color_hex' => '#9E9E9E',
                        'sku' => 'STM-CRW-GRY-XL',
                        'additional_price' => 15000.00,
                        'stock_quantity' => 5,
                    ],
                    [
                        'id' => 137,
                        'size' => 'S',
                        'color_name' => 'Midnight Navy',
                        'color_hex' => '#1B263B',
                        'sku' => 'STM-CRW-NAV-S',
                        'additional_price' => 0.00,
                        'stock_quantity' => 6,
                    ],
                    [
                        'id' => 138,
                        'size' => 'M',
                        'color_name' => 'Midnight Navy',
                        'color_hex' => '#1B263B',
                        'sku' => 'STM-CRW-NAV-M',
                        'additional_price' => 0.00,
                        'stock_quantity' => 9,
                    ],
                    [
                        'id' => 139,
                        'size' => 'L',
                        'color_name' => 'Midnight Navy',
                        'color_hex' => '#1B263B',
                        'sku' => 'STM-CRW-NAV-L',
                        'additional_price' => 0.00,
                        'stock_quantity' => 8,
                    ],
                    [
                        'id' => 140,
                        'size' => 'XL',
                        'color_name' => 'Midnight Navy',
                        'color_hex' => '#1B263B',
                        'sku' => 'STM-CRW-NAV-XL',
                        'additional_price' => 15000.00,
                        'stock_quantity' => 4,
                    ],
                ],
            ],

            // 6. Stars Tactical Multi-Pocket Cargo (Pants & Cargo)
            [
                'id' => 6,
                'category_id' => 3,
                'name' => 'Stars Tactical Multi-Pocket Cargo',
                'slug' => 'stars-tactical-multi-pocket-cargo',
                'description' => 'Celana cargo teknis dengan 6 kantong fungsional, bahan katun ripstop kokoh anti-sobek, serta tali serut adjustable di pergelangan kaki untuk fleksibilitas gaya jogger maupun straight fit.',
                'base_price' => 329000,
                'is_featured' => true,
                'is_active' => true,
                'images' => [
                    [
                        'image_url' => 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800&auto=format&fit=crop&q=80',
                        'alt_text' => 'Tampak Depan - Stars Tactical Multi-Pocket Cargo',
                        'is_primary' => true,
                        'sort_order' => 1,
                    ],
                    [
                        'image_url' => 'https://images.unsplash.com/photo-1517445312882-bc9910d016b7?w=800&auto=format&fit=crop&q=80',
                        'alt_text' => 'Detail Kantong - Stars Tactical Multi-Pocket Cargo',
                        'is_primary' => false,
                        'sort_order' => 2,
                    ],
                ],
                'variants' => [
                    [
                        'id' => 141,
                        'size' => 'S',
                        'color_name' => 'Army Olive',
                        'color_hex' => '#3B413A',
                        'sku' => 'STM-CRG-OLV-S',
                        'additional_price' => 0.00,
                        'stock_quantity' => 7,
                    ],
                    [
                        'id' => 142,
                        'size' => 'M',
                        'color_name' => 'Army Olive',
                        'color_hex' => '#3B413A',
                        'sku' => 'STM-CRG-OLV-M',
                        'additional_price' => 0.00,
                        'stock_quantity' => 11,
                    ],
                    [
                        'id' => 143,
                        'size' => 'L',
                        'color_name' => 'Army Olive',
                        'color_hex' => '#3B413A',
                        'sku' => 'STM-CRG-OLV-L',
                        'additional_price' => 0.00,
                        'stock_quantity' => 9,
                    ],
                    [
                        'id' => 144,
                        'size' => 'XL',
                        'color_name' => 'Army Olive',
                        'color_hex' => '#3B413A',
                        'sku' => 'STM-CRG-OLV-XL',
                        'additional_price' => 15000.00,
                        'stock_quantity' => 4,
                    ],
                    [
                        'id' => 145,
                        'size' => 'S',
                        'color_name' => 'Matte Black',
                        'color_hex' => '#1A1A1A',
                        'sku' => 'STM-CRG-BLK-S',
                        'additional_price' => 0.00,
                        'stock_quantity' => 10,
                    ],
                    [
                        'id' => 146,
                        'size' => 'M',
                        'color_name' => 'Matte Black',
                        'color_hex' => '#1A1A1A',
                        'sku' => 'STM-CRG-BLK-M',
                        'additional_price' => 0.00,
                        'stock_quantity' => 14,
                    ],
                    [
                        'id' => 147,
                        'size' => 'L',
                        'color_name' => 'Matte Black',
                        'color_hex' => '#1A1A1A',
                        'sku' => 'STM-CRG-BLK-L',
                        'additional_price' => 0.00,
                        'stock_quantity' => 12,
                    ],
                    [
                        'id' => 148,
                        'size' => 'XL',
                        'color_name' => 'Matte Black',
                        'color_hex' => '#1A1A1A',
                        'sku' => 'STM-CRG-BLK-XL',
                        'additional_price' => 15000.00,
                        'stock_quantity' => 5,
                    ],
                ],
            ],

            // 7. Stars Relaxed Fit Denim Pants (Pants & Cargo)
            [
                'id' => 7,
                'category_id' => 3,
                'name' => 'Stars Relaxed Fit Denim Pants',
                'slug' => 'stars-relaxed-fit-denim-pants',
                'description' => 'Celana jeans 13.5 oz non-stretch denim dengan potongan relaxed straight leg dan efek washing vintage autentik. Memberikan siluet streetwear klasik dengan kenyamanan maksimal.',
                'base_price' => 359000,
                'is_featured' => false,
                'is_active' => true,
                'images' => [
                    [
                        'image_url' => 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&auto=format&fit=crop&q=80',
                        'alt_text' => 'Tampak Depan - Stars Relaxed Fit Denim Pants',
                        'is_primary' => true,
                        'sort_order' => 1,
                    ],
                    [
                        'image_url' => 'https://images.unsplash.com/photo-1542272604-780c96856592?w=800&auto=format&fit=crop&q=80',
                        'alt_text' => 'Detail Denim - Stars Relaxed Fit Denim Pants',
                        'is_primary' => false,
                        'sort_order' => 2,
                    ],
                ],
                'variants' => [
                    [
                        'id' => 149,
                        'size' => 'S',
                        'color_name' => 'Vintage Light Wash',
                        'color_hex' => '#7C92A6',
                        'sku' => 'STM-DNM-LGT-S',
                        'additional_price' => 0.00,
                        'stock_quantity' => 5,
                    ],
                    [
                        'id' => 150,
                        'size' => 'M',
                        'color_name' => 'Vintage Light Wash',
                        'color_hex' => '#7C92A6',
                        'sku' => 'STM-DNM-LGT-M',
                        'additional_price' => 0.00,
                        'stock_quantity' => 8,
                    ],
                    [
                        'id' => 151,
                        'size' => 'L',
                        'color_name' => 'Vintage Light Wash',
                        'color_hex' => '#7C92A6',
                        'sku' => 'STM-DNM-LGT-L',
                        'additional_price' => 0.00,
                        'stock_quantity' => 7,
                    ],
                    [
                        'id' => 152,
                        'size' => 'XL',
                        'color_name' => 'Vintage Light Wash',
                        'color_hex' => '#7C92A6',
                        'sku' => 'STM-DNM-LGT-XL',
                        'additional_price' => 15000.00,
                        'stock_quantity' => 3,
                    ],
                    [
                        'id' => 153,
                        'size' => 'S',
                        'color_name' => 'Raw Indigo',
                        'color_hex' => '#1F2937',
                        'sku' => 'STM-DNM-IND-S',
                        'additional_price' => 0.00,
                        'stock_quantity' => 6,
                    ],
                    [
                        'id' => 154,
                        'size' => 'M',
                        'color_name' => 'Raw Indigo',
                        'color_hex' => '#1F2937',
                        'sku' => 'STM-DNM-IND-M',
                        'additional_price' => 0.00,
                        'stock_quantity' => 10,
                    ],
                    [
                        'id' => 155,
                        'size' => 'L',
                        'color_name' => 'Raw Indigo',
                        'color_hex' => '#1F2937',
                        'sku' => 'STM-DNM-IND-L',
                        'additional_price' => 0.00,
                        'stock_quantity' => 8,
                    ],
                    [
                        'id' => 156,
                        'size' => 'XL',
                        'color_name' => 'Raw Indigo',
                        'color_hex' => '#1F2937',
                        'sku' => 'STM-DNM-IND-XL',
                        'additional_price' => 15000.00,
                        'stock_quantity' => 4,
                    ],
                ],
            ],

            // 8. Stars Signature 6-Panel Dad Cap (Accessories)
            [
                'id' => 8,
                'category_id' => 4,
                'name' => 'Stars Signature 6-Panel Dad Cap',
                'slug' => 'stars-signature-6-panel-dad-cap',
                'description' => 'Topi baseball 6-panel dengan bahan katun twill berkualitas dan bordir Stars Merch 3D di bagian depan. Dilengkapi strap gesper logam di belakang untuk ukuran yang dapat disesuaikan.',
                'base_price' => 129000,
                'is_featured' => false,
                'is_active' => true,
                'images' => [
                    [
                        'image_url' => 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=800&auto=format&fit=crop&q=80',
                        'alt_text' => 'Tampak Depan - Stars Signature 6-Panel Dad Cap',
                        'is_primary' => true,
                        'sort_order' => 1,
                    ],
                    [
                        'image_url' => 'https://images.unsplash.com/photo-1575428652377-a2d80e2277fc?w=800&auto=format&fit=crop&q=80',
                        'alt_text' => 'Tampak Samping - Stars Signature 6-Panel Dad Cap',
                        'is_primary' => false,
                        'sort_order' => 2,
                    ],
                ],
                'variants' => [
                    [
                        'id' => 157,
                        'size' => 'OS',
                        'color_name' => 'Obsidian Black',
                        'color_hex' => '#111111',
                        'sku' => 'STM-CAP-BLK-OS',
                        'additional_price' => 0.00,
                        'stock_quantity' => 25,
                    ],
                    [
                        'id' => 158,
                        'size' => 'OS',
                        'color_name' => 'Chalk White',
                        'color_hex' => '#EAEAEA',
                        'sku' => 'STM-CAP-WHT-OS',
                        'additional_price' => 0.00,
                        'stock_quantity' => 18,
                    ],
                ],
            ],
        ];

        foreach ($products as $prodData) {
            $images = $prodData['images'];
            $variants = $prodData['variants'];
            unset($prodData['images'], $prodData['variants']);

            $product = Product::updateOrCreate(['id' => $prodData['id']], $prodData);

            foreach ($images as $imgData) {
                ProductImage::updateOrCreate([
                    'product_id' => $product->id,
                    'sort_order' => $imgData['sort_order'],
                ], array_merge($imgData, ['product_id' => $product->id]));
            }

            foreach ($variants as $varData) {
                ProductVariant::updateOrCreate(
                    ['id' => $varData['id']],
                    array_merge($varData, ['product_id' => $product->id])
                );
            }
        }
    }
}
